include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    directives_ordering: true
    prefer_const_constructors: true
    require_trailing_commas: true
    unawaited_futures: true